### PR TITLE
Generate tests from spec document

### LINKED ISSUE #129: Generate tests from the spec?
As far as I can tell, I do not see a test for this rule within the spec

>  The [table] form can, however, be used to define sub-tables within tables defined via dotted keys.

I was starting to write a test but I realized we could possibly code-generate tests from the spec seeing as the spec follows a specific pattern in marking whole documents invalid or specific parts.

Before starting on that, I wanted to gauge interest and preferred method for pulling in the toml.io repo (sub-module, sub-tree, having users do it by hand, etc) and if there is anything with versioning we should do (I feel like the json should be extended with versioning information rather than embedding it within the binary but the simplest to unblock is to only generate for the latest spec).

### PR DESCRIPTION
**Pull request by epage**
I used "header + fence index within header" to try to give some level of stability to the file names across changes (as compared to using line numbers)

Fixes #129

### CODE REVIEW

**Comment by arp242** [comment]
Ah, I had misunderstood the issue you reported earlier; what I *thought* you meant was to take the ABNF file and use that to generate a whole bunch of permutations based on the syntax description in there.

**Comment by arp242** [comment]
https://github.com/BurntSushi/toml-test/commit/3b92c714b6f4f4d370eb3b0e12fcd143411dd773

The JSON files changed because the output is a bit different (ordered alphabetically by key), but they should be semantically identical.

**Comment by epage** [comment]
Thanks for fixing up the json files!  I assumed my formatting was off than expected but I wasn't sure if there was a standard way of generating them (the README doesn't mention a "write out json" for writing tests) and I don't have a go toolchain setup

**Comment by arp242** [comment]
> I wasn't sure if there was a standard way of generating them 

There wasn't until I thought of it yesterday 🙃 I always did it manually before and then yesterday I facepalmed and realized I can use `toml-test-decoder` for this.

**Comment by arp242** [comment]
I merged both gen-*.py` files to `gen.py` and merged it; thanks!

**Pull request merged**
