### PR TITLE
Use more standard float formatting in two tests

### PR DESCRIPTION
**Pull request by filmor**

### CODE REVIEW

**Comment by arp242** [comment]
What problem does this solve? Because both values are identical, right?

**Comment by arp242** [comment]
Oh, I see your [other comment](https://github.com/BurntSushi/toml-test/issues/670 now.

You should really compare these things semantically rather than a string comparison. Implementations may choose to format float `5` as `5`, `5.00`, etc. or `3e14` as `3E14`. It's all identical, and it's impossible for a generic test case to satisfy everyone's needs.

**Comment by filmor** [comment]
Not being able to parse `3e14` is relatively common with stricter parsers, though. I am comparing things "semantically" now, but for this to work for all inputs one may put, I'd need to first build a parser that works like go's to make use of the corpus in my test suite. I can deal with adjusting the tests from time to time, but I guess it would also not be a problem to adhere to a relatively strict rule to simplify for other test runners.

**Comment by filmor** [comment]
Regarding why it matters: The test suite stores numerical values as strings (because JSON doesn't strictly distinguish ints and floats), but that also means that alternative test runner implementations have to deal with the comparison logic. For all other types this is trivial (in particular, even for dates) just floats are problematic.

**Comment by arp242** [comment]
> The test suite stores numerical values as strings (because JSON doesn't strictly distinguish ints and floats)

I don't think this should really a problem? Languages are free to just interpret `50` as an integer; no need to have the JSON/JavaScript float/int confusion.

This patch won't hurt anyone else I guess (unless they're also doing string comparisons but with different expectations, but like I said, IMHO that's a bad idea in the first place), so I don't see any reason to not merge it if if it solves practical issues for you; but I think you'll probably run in to more problems down the line with this(?)

**Comment by arp242** [comment]
Also, they're represented as `{"type": "float", value: "42"}` in the JSON, so you *know* it will be a float or integer anyway because of the type hints in there. I don't know Erlang so I can't really follow your code, but I'm fairly sure this can just be fixed in there so that `1.0` and `1` both work equally well.

**Pull request merged**
